//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXIWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_DETALLE
    {
        public int ID { get; set; }
        public Nullable<int> ID_PEDIDO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public int PRODUCTO_CANTIDAD { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
